### ISSUE TITLE
Can't get this project to run 

### ISSUE THREAD

**Issue by urbanintell** [EkoCommunications/UpstraUIKitiOSSample#1]
I am getting the following error message when running 'pod install' or 'pod install --repo-update'

`Traceback (most recent call last):
	32: from /usr/local/bin/pod:23:in `<main>'
	31: from /usr/local/bin/pod:23:in `load'
	30: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/bin/pod:55:in `<top (required)>'
	29: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:52:in `run'
	28: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	27: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command/install.rb:52:in `run'
	26: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:167:in `install!'
	25: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:180:in `integrate'
	24: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:301:in `generate_pods_project'
	23: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:309:in `create_and_save_projects'
	22: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:64:in `section'
	21: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:314:in `block in create_and_save_projects'
	20: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:19:in `generate!'
	19: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:31:in `install_all_pod_targets'
	18: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:149:in `message'
	17: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:32:in `block in install_all_pod_targets'
	16: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:112:in `install_pod_targets'
	15: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:112:in `map'
	14: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:115:in `block in install_pod_targets'
	13: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:40:in `install!'
	12: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:149:in `message'
	11: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:69:in `block in install!'
	10: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/target/pod_target.rb:444:in `xcframeworks'
	 9: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/target/pod_target.rb:444:in `each_with_object'
	 8: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/target/pod_target.rb:444:in `each'
	 7: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/target/pod_target.rb:445:in `block in xcframeworks'
	 6: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/target/pod_target.rb:445:in `map'
	 5: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/target/pod_target.rb:446:in `block (2 levels) in xcframeworks'
	 4: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/target/pod_target.rb:446:in `new'
	 3: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/xcode/xcframework.rb:41:in `initialize'
	 2: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
	 1: from /Library/Ruby/Gems/2.6.0/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:110:in `parse!'
/Library/Ruby/Gems/2.6.0/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:284:in `raise_parser_error': [!] Found additional characters after parsing the root plist object (Nanaimo::Reader::ParseError)
 #  -------------------------------------------
1>  version https://git-lfs.github.com/spec/v1
            ^
 #  oid sha256:8a44041eed536683e9aa66d17ac4dbd8279e040897a6675e6827fe5cfc9b121a
 #  size 1141
 #  -------------------------------------------
	9: from /usr/local/bin/pod:23:in `<main>'
	8: from /usr/local/bin/pod:23:in `load'
	7: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/bin/pod:55:in `<top (required)>'
	6: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:52:in `run'
	5: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'
	4: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
	3: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
	2: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:66:in `report_error'
	1: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface/error_report.rb:34:in `report'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface/error_report.rb:34:in `force_encoding': can't modify frozen String (FrozenError)`

**Comment by urbanintell** [comment]
pod file should just be 


`# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'UpstraUIKitiOSSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UpstraUIKitiOSSample
  pod 'AmityUIKit'

  target 'UpstraUIKitiOSSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UpstraUIKitiOSSampleUITests' do
    # Pods for testing
  end

end
`

**Comment by urbanintell** [comment]
update amity to latest version in Podfile

pod 'AmityUIKit'
